export const players = [
  {
    id: '1',
    name: 'Lebron James',
    age: '34',
    club: 'LA Lakers',
    MVP: '4',
    FMVP: '4',
  },
  {
    id: '2',
    name: 'Kevin Durant',
    age: '30',
    club: 'Brooklyn Nets',
    MVP: '1',
    FMVP: '2',
  },
  {
    id: '3',
    name: 'Carmelo Anthony',
    age: '34',
    club: 'Portland Trail Blazers',
    MVP: '0',
    FMVP: '0',
  },
  {
    id: '4',
    name: 'Stephen Curry',
    age: '30',
    club: 'Golden state warriors',
    MVP: '3',
    FMVP: '0',
  },
  {
    id: '5',
    name: 'Klay Thompson',
    age: '30',
    club: 'Golden state warriors',
    MVP: '0',
    FMVP: '0',
  },
  {
    id: '6',
    name: 'Paul George',
    age: '30',
    club: 'LA clippers',
    MVP: '0',
    FMVP: '0',
  },
  {
    id: '7',
    name: 'Kwahi Leonard',
    age: '32',
    club: 'LA Clippers',
    MVP: '0',
    FMVP: '3',
  },
  {
    id: '8',
    name: 'Kyrie Irving',
    age: '29',
    club: 'Brooklyn Nets',
    MVP: '0',
    FMVP: '0',
  },
  {
    id: '9',
    name: 'James Harden',
    age: '32',
    club: 'Brooklyn Nets',
    MVP: '1',
    FMVP: '0',
  },
  {
    id: '10',
    name: 'Damian Lillard',
    age: '30',
    club: 'Portland Trailblazers',
    MVP: '0',
    FMVP: '0',
  },
  {
    id: '12',
    name: 'Giannis Antemtokumopo',
    age: '28',
    club: 'Millwaukee bucks',
    MVP: '2',
    FMVP: '0',
  },
  {
    id: '13',
    name: 'Andrea Iguodula',
    age: '37',
    club: 'Miami Heats',
    MVP: '0',
    FMVP: '2',
  },
]
